# Generated by Django 3.2.6 on 2023-12-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.webp', upload_to='profile_pics/'),
        ),
    ]
